### ISSUE TITLE
How to edit the cell

### ISSUE THREAD

**Issue by winpzs** [mazdik/ng-crud-table#1]
for example:
```
this.table.editCell(rowIndex, cellIndex)
```

**Comment by mazdik** [comment]
Move focus to this cell and switch it to the editable mode?
    import {CellEventArgs} from '../../ng-data-table/types';
    this.table.events.onDblClickCell(<CellEventArgs>{columnIndex: 2, rowIndex: 0});
Or update the value of the cell?
    this.table.rows[0]['name'] = 'new value';
    this.table.events.onRowsChanged();

**Comment by winpzs** [comment]
for example:
```typescript
  editRow() {
    let rowIndex = 0;
    let editMode = true;
    for (let columnIndex = 1; columnIndex < 6; columnIndex++)
      this.table.cellEditMode(rowIndex, columnIndex, editMode);
  }
```

**Comment by mazdik** [comment]
Added function: editCell(rowIndex: number, columnIndex: number, editMode: boolean) 
[https://github.com/mazdik/ng-crud-table/commit/c066ca65357396a2f3ccbe4b91888d7ce6a768ca](url)
  public settings: Settings = {
    editMode: 'editProgrammatically'
  };

**Comment by winpzs** [comment]
thanks
