### ISSUE TITLE
This project is very good , can you add function for export to xls ?

### ISSUE THREAD

**Issue by huangwei16800** [mazdik/ng-crud-table#10]
this data table is so nice, i like it, i will use in my project (MIS SYSTEM), but how can  export to Excel .
because My user always export data to Excel

**Comment by mazdik** [comment]
Try js-xlsx
[demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/src/app/sheetjs.component.ts)

`
	export(): void {
		const ws: XLSX.WorkSheet = XLSX.utils.json_to_sheet(this.dataManager.rows);
		const wb: XLSX.WorkBook = XLSX.utils.book_new();
		XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
		XLSX.writeFile(wb, this.fileName);
	}
`

**Comment by huangwei16800** [comment]
thank your!
