### ISSUE TITLE
How to create multi-select dropdown?

### ISSUE THREAD

**Issue by kontacthimanshu** [mazdik/ng-crud-table#13]
Hi,

I am trying to use ng-crud-table and in the table I need to create a multi-select dropdown. Can you please suggest how I can do that?

**Comment by mazdik** [comment]
Hi, 
[Sample](https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/multi-select-demo.component.ts)

**Comment by kontacthimanshu** [comment]
Thanks a ton for quick turnaround. Your library is amazing!!
