### ISSUE TITLE
Edit cell with dependsColumn not working

### ISSUE THREAD

**Issue by fazr** [mazdik/ng-crud-table#19]
In the basic demo, the "Cascading Select" is depending on the column "Race".
Here I attached the image :

![image](https://user-images.githubusercontent.com/21077745/57431961-043fd180-7267-11e9-8824-7deb95c75a65.png)

But as you can see the column "Cascading Select" is displaying all the options without depending on the column "Race". But in update dialog it depends on the column "Race". 
Here I attached the image : 

![image](https://user-images.githubusercontent.com/21077745/57432074-5c76d380-7267-11e9-827d-085b43a30c63.png)

Is this intentional or bug ? If this intentional can u help with workaround for edit in cell able to dependsColumn. 

Thanks !

**Comment by mazdik** [comment]
Hi,
[Fixed](https://github.com/mazdik/ng-crud-table/commit/f6abe608e5729a7aa2ca528c846274bd5d3ae372)

**Comment by fazr** [comment]
great work man. thanks !
