### ISSUE TITLE
select-dropdown first option not working on first select

### ISSUE THREAD

**Issue by hghew** [mazdik/ng-crud-table#20]
for type "select-dropdown" in data table, when it is empty selection initially, during selecting first option and navigate away, it will always empty, have to select second option or else then only selecting back option one success.

Thanks.

**Comment by mazdik** [comment]
Can I get screenshots?

**Comment by hghew** [comment]
using latest, frop select-dropdown, when initially none is select, selecting first option will always show empty, selecting all other options and then selecting first one is ok
![Untitled](https://user-images.githubusercontent.com/50605037/57739068-b30b6400-76e4-11e9-9b8b-bd1376221691.png)

**Comment by mazdik** [comment]
[Fixed](https://github.com/mazdik/ng-crud-table/commit/81f8e0e8f9f2644d77a0248773dab7005f5b313d)

**Comment by hghew** [comment]
thanks alot
