### ISSUE TITLE
headerRowHeight css can setting to 20px from 40px?

### ISSUE THREAD

**Issue by huangwei16800** [mazdik/ng-crud-table#21]
usually datable display data,  RowHeight no need too high.
i had modify min-height to 25px.  and rowHeight i want to setting to 25 ,but char not center align
.datatable-header-row {
  min-height: 20px;
}

**Comment by huangwei16800** [comment]
![pro1](https://user-images.githubusercontent.com/28200737/57964709-fde6df00-7963-11e9-849a-ddb4233bac08.JPG)

**Comment by mazdik** [comment]
[removed min-height](https://github.com/mazdik/ng-crud-table/commit/e508399402b9937da9fa8a30b80923cf1f9b1830)

**Comment by huangwei16800** [comment]
thank your!    i will use ng-crud-table in my project,
