### ISSUE TITLE
 cell font-size,can your add font-size&line-height binding?

### ISSUE THREAD

**Issue by huangwei16800** [mazdik/ng-crud-table#22]
can you add @HostBinding('style.font-size.px') and line-height ?  we can define the cell font-size and line-height , so ,function same as Powerbuilder ( DataWindow)
because  I make ng-curd-table to web elements, no need setting global css

dt-body-cell-edit tabindex="-1" ng-reflect-table="[object Object]" ng-reflect-cell="[object Object]" class="datatable-body-cell dt-sticky" role="gridcell" data-column-index="1" data-row-index="0" style="**_line-height: 1.3;font-size:12px;_**width: 200px; left: 140px;"

**Comment by huangwei16800** [comment]
if not define font-size,default null,use global body.font-size. if define, use body-cell 's font-size style

**Comment by mazdik** [comment]
try as in these examples:
[sample1](https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/multi-select-demo.component.ts)
[sample2](https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/vertical-group-demo.component.ts)
```html
<app-crud-table class="your-custom-class" [dataManager]="dataManager"></app-crud-table>
```
