### ISSUE TITLE
'position', 'sticky' not support in chrome 49-50

### ISSUE THREAD

**Issue by huangwei16800** [mazdik/ng-crud-table#30]
can add CSS.supports("position", "sticky") to check ?
![sticky](https://user-images.githubusercontent.com/28200737/59243256-2f885880-8c39-11e9-81f9-5ea3f176194c.png)

**Comment by mazdik** [comment]
[supportsStickyPosition added](https://github.com/mazdik/ng-crud-table/commit/355773112fac7be64ccdbb97157e29d5ed14d596)

**Comment by huangwei16800** [comment]
thank you!  now work ok.
