### ISSUE TITLE
Is there any way resolve Tree Checkbox Selection Issue on collapse / expand

### ISSUE THREAD

**Issue by suryakanta101** [mazdik/ng-crud-table#31]
![image](https://user-images.githubusercontent.com/3184991/59267270-5fe6eb80-8c67-11e9-9b7c-7570a259dfb0.png)

When we are check Tree Checkbox and then Collapse -> Expand again, the previous selection is not there. But the selection showing in CSS UI

**Comment by mazdik** [comment]
You can customize the table by example:
[demo](https://mazdik.github.io/ng-crud-table/#/tree-table-custom-demo)
[source](https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/tree-table-custom-demo.component.ts)

**Comment by suryakanta101** [comment]
![image](https://user-images.githubusercontent.com/3184991/59272763-5adc6900-8c74-11e9-9003-d0498fca467f.png)

With 
selectionMultiple: true,
selectionMode: 'checkbox', 

Selection All is working fine, but when we "uncheck" the Tree node, it should uncheck children nodes as well. What config do we need here?

**Comment by suryakanta101** [comment]
Also, there seems to be a UI issue , if not mistaken. After a collapse here, if there is scroll down, it is a slight visible data looks something hiding.

![image](https://user-images.githubusercontent.com/3184991/59285469-ac442280-8c8b-11e9-94c5-525265c95bfc.png)

**Comment by mazdik** [comment]
look at the last commit, there were more folder icons

**Comment by suryakanta101** [comment]
I think this is not about the folder icons.  It seems the Rows are hidden and merged . See the image below.

After a row collapse , the hidden rows are visible below.

![image](https://user-images.githubusercontent.com/3184991/59286062-ac90ed80-8c8c-11e9-9fe1-71b91c1f1464.png)

**Comment by suryakanta101** [comment]
`.datatable-body-row, .datatable-header-row {
    display: -webkit-box;
    position: relative;
}`

following css code changes making the above issue fixed.

**Comment by suryakanta101** [comment]
@mazdik Is there any flag , to make initially all Tree Table in collapsed state.

**Comment by mazdik** [comment]
> @mazdik Is there any flag , to make initially all Tree Table in collapsed state.
in prepareTreeData:
```js
    rows.forEach(x => {
      x.$$height = (x.$$level > 1) ? 0 : null;
      x.expanded = !(x.$$level > 0);
    });
```

**Comment by mazdik** [comment]
> `.datatable-body-row, .datatable-header-row { display: -webkit-box; position: relative; }`
> 
> following css code changes making the above issue fixed.

is old 2009 version of Flexbox
[“Old” Flexbox and “New” Flexbox](https://css-tricks.com/old-flexbox-and-new-flexbox/)

```css
.datatable-body-row[style*="height: 0"] {
  overflow-y: hidden; /* or display: none; */
}
```
