### ISSUE TITLE
JSON structure generalisation

### ISSUE THREAD

**Issue by suryakanta101** [mazdik/ng-crud-table#32]
Hello @mazdik 

you have defined JSON as per the datatable demand.. If we want to change the json attribute names (i.e data, children   to dataEntity, ChildrenEntity) different name, then do we need to change the core files in tree.ts , tree-node.ts etc ???

`[
  {
    "id": "ASMODIANS",
    "name": "ASMODIANS",
    "dataEntity": {
      "name": "Defunct",
      "gender": "MALE",
      "cube_size": "1",
      "exp": 777777
    },
    "ChildrenEntity": [
      {
        "id": "MALE",
        "name": "MALE",`

**Comment by mazdik** [comment]
Need to change JSON attribute names. Or you can use TreeFlattener and TreeBuilder.
