### ISSUE TITLE
tree table how to get selected rows

### ISSUE THREAD

**Issue by winpzs** [mazdik/ng-crud-table#4]
tree table how to get selected rows

**Comment by mazdik** [comment]
Tree table is updated.
`
<app-tree-table [treeTable]="treeTable"></app-tree-table>

  constructor(private http: HttpClient) {
    this.treeService = new TreeDemoService(this.http);
    this.treeTable = new TreeTable(this.columns, this.settings, this.treeService);
// without data source:  this.treeTable.nodes = ...
  }

  ngOnInit() {
    const subSelection = this.treeTable.events.selectionSource$.subscribe(() => {
      console.log(this.treeTable.selectedNode);
    });
  }
`

Demo:
https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/tree-table-demo.component.ts
