### ISSUE TITLE
No Horizontal Scroll Bar for Frozen Column.

### ISSUE THREAD

**Issue by suryakanta101** [mazdik/ng-crud-table#45]
Hello @mazdik 

 Can you add one example in demo section , where we also have Fixed Frozen Column with no Horizontal Scroll Bar for it.

Is it possible to have Scroll Bar (Horizontal)  starting from the scrollable column. For the Frozen columns , there no scroll bar present as visible following picture.  

Update >>>

@mazdik , you have CSS blog where (http://mazdik.ru/note/css/table-with-fixed-headers-and-left-columns-v4) have the same behavior.

Do above behavior possible in Data Table with Frozen Column ?

**Comment by suryakanta101** [comment]
@mazdik 

How is the way of Implementation to hide the default Scroll of the Datatable, and add Dummy Scroll at 
the correct position and link it to DataTable Scroll.

ngOnInit() {
    window.addEventListener('scroll', this.scrollEvent, true);
}

scrollEvent = (event: any): void => {
    this.table.dimensions.offsetY = event.scrollYPos;
    this.table.dimensions.offsetX = event.scrollXPos;
    this.table.events.onScroll(event);
}

**Comment by mazdik** [comment]
[left frozen table demo](https://github.com/mazdik/ng-crud-table/blob/master/src/app/demo/frozen-table-demo.component.ts)

**Comment by suryakanta101** [comment]
Thank you @mazdik , it works well for Basic Table.

But for the Tree Table, all the rows of Frozen Left Column in expand state.
Can we retrieve the Expand Collapse properties here. Also can the Checkbox move here to Frozen Column ?
