### ISSUE TITLE
getOptions  in service

### ISSUE THREAD

**Issue by altemir1992** [mazdik/ng-crud-table#5]
I'm using ASP NET CORE in back-end,  when I call the method this.service.getOptions for populate select-options component. 
Method:
```
  loadOptions() {
    if (this.column.optionsUrl && this.service.getOptions) {
      this.loading = true;
      this.service.getOptions(this.column.optionsUrl, this._dependsValue).then((res) => {
        this._options = res;
        this.loading = false;
        this.setDefaultSelect();
      }).catch(error => {
        this._options = [];
        this.loading = false;
      });
    }
  }
```

This method receive one array the options.

```
@Input()
  set options(val: any[]) {
    this._options = val;
    if (this._options) {
      this.optionsCopy = [...val];
    }
    this.selectedName = this.getName();
  }
```

But with the request processing time, the initial value becomes undefined, and thus does not populate the ModalSelectComponent.

Getting in load, however when clicking under the modal page, the already processed value is loaded normally.

What can be done for this case?

**Comment by mazdik** [comment]
{ 
   	  name: 'x_id',
      tableHidden: true,
      formHidden: true
    },
    {
      name: 'x_name',
      keyColumn: 'x_id',
      optionsUrl: environment.host + '/dict/x_names',
      type: 'select-popup'
    },
Have you tried this option?
For example, what are your columns?

**Comment by altemir1992** [comment]
yes, it's exactly the same. The problem is that Promise does not populate the variable this._options at first, because it is still being rendered in the back end of the result, so the variable this.optionsCopy gets undefined.

**Comment by mazdik** [comment]
Is this error (undefined) displayed in the console?
Change detection is not working?

**Comment by altemir1992** [comment]
The event nameChanged resolved the problem.

Tks.

**Comment by altemir1992** [comment]
The input-option.component not working now.

value is null in event valueChanged.

```

 onValueChange() {
    if (this.column.keyColumn) {
      this.keyColumnChange.emit({
        'column': this.column.keyColumn,
        'value': this.model
      });
    }
  }
```
this.model ever null.

**Comment by mazdik** [comment]
[fixed](https://github.com/mazdik/ng-crud-table/commit/c670c909a7131869715e0f83ee969e41d4aa8a72)

**Comment by altemir1992** [comment]
Tks 👍
